import type { KnownTool } from './types';

export const KNOWN_TOOLS: KnownTool[] = [
  // --- Productivity & Collaboration ---
  {
    slug: 'microsoft-365',
    name: 'Microsoft 365',
    provider: 'Microsoft',
    category: 'Productivity',
    score: {
      jurisdiction: 4,
      continuity: 2,
      surveillance: 4,
      lockIn: 4,
      costExposure: 3,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction (CLOUD Act); deep ecosystem lock-in; extensive telemetry collection; price increases on renewal',
    estimatedAnnualCost: 1200,
    pricing: {
      model: 'tiered',
      penetrationRate: 1.0,
      tiers: [
        { name: 'Business Basic', maxUsers: 300, annualPerSeat: 54, recommended: true, minUsers: 1 },
        { name: 'Business Standard', maxUsers: 300, annualPerSeat: 114 },
        { name: 'Enterprise E3', annualPerSeat: 264, minUsers: 50 },
        { name: 'Enterprise E5', annualPerSeat: 432, minUsers: 100 },
      ],
    },
  },
  {
    slug: 'google-workspace',
    name: 'Google Workspace',
    provider: 'Google',
    category: 'Productivity',
    score: {
      jurisdiction: 4,
      continuity: 2,
      surveillance: 5,
      lockIn: 4,
      costExposure: 3,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; aggressive data mining for advertising profiles; deep ecosystem lock-in; export tools exist but migration is complex',
    estimatedAnnualCost: 960,
    pricing: {
      model: 'tiered',
      penetrationRate: 1.0,
      tiers: [
        { name: 'Business Starter', maxUsers: 300, annualPerSeat: 50, recommended: true },
        { name: 'Business Standard', maxUsers: 300, annualPerSeat: 96 },
        { name: 'Business Plus', maxUsers: 300, annualPerSeat: 144 },
        { name: 'Enterprise', annualPerSeat: 252, minUsers: 50 },
      ],
    },
  },
  {
    slug: 'slack',
    name: 'Slack',
    provider: 'Salesforce',
    category: 'Communication',
    score: {
      jurisdiction: 4,
      continuity: 3,
      surveillance: 3,
      lockIn: 3,
      costExposure: 3,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; message history limits on free tier; data accessible to workspace admins; vendor acquired by Salesforce',
    estimatedAnnualCost: 840,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.8,
      tiers: [
        { name: 'Free', annualPerSeat: 0, maxUsers: 999, recommended: true },
        { name: 'Pro', annualPerSeat: 63 },
        { name: 'Business+', annualPerSeat: 105, minUsers: 25 },
      ],
    },
  },
  {
    slug: 'zoom',
    name: 'Zoom',
    provider: 'Zoom',
    category: 'Communication',
    score: {
      jurisdiction: 4,
      continuity: 2,
      surveillance: 3,
      lockIn: 2,
      costExposure: 3,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; past security controversies; data routed through multiple jurisdictions; relatively easy to switch',
    estimatedAnnualCost: 1200,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.5,
      tiers: [
        { name: 'Basic', annualPerSeat: 0, maxUsers: 100, recommended: true },
        { name: 'Pro', annualPerSeat: 120 },
        { name: 'Business', annualPerSeat: 180, minUsers: 10 },
      ],
    },
  },
  {
    slug: 'teams',
    name: 'Microsoft Teams',
    provider: 'Microsoft',
    category: 'Communication',
    score: {
      jurisdiction: 4,
      continuity: 2,
      surveillance: 4,
      lockIn: 4,
      costExposure: 3,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; bundled with M365 creating lock-in; extensive telemetry; tightly coupled to Microsoft ecosystem',
    estimatedAnnualCost: 0,
  },

  // --- CRM & Sales ---
  {
    slug: 'salesforce',
    name: 'Salesforce',
    provider: 'Salesforce',
    category: 'CRM',
    score: {
      jurisdiction: 4,
      continuity: 2,
      surveillance: 3,
      lockIn: 5,
      costExposure: 5,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; extreme lock-in through customisation; very high costs and complex pricing; data export is difficult',
    estimatedAnnualCost: 3000,
    pricing: {
      model: 'per_seat',
      penetrationRate: 0.3,
      annualPerSeat: 300,
      tiers: [
        { name: 'Essentials', annualPerSeat: 300, recommended: true, maxUsers: 10 },
        { name: 'Professional', annualPerSeat: 900, minUsers: 5 },
        { name: 'Enterprise', annualPerSeat: 1800, minUsers: 20 },
      ],
    },
  },
  {
    slug: 'hubspot',
    name: 'HubSpot',
    provider: 'HubSpot',
    category: 'CRM',
    score: {
      jurisdiction: 4,
      continuity: 2,
      surveillance: 3,
      lockIn: 4,
      costExposure: 4,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; significant lock-in through workflows and integrations; escalating costs as contacts grow; free tier limited',
    estimatedAnnualCost: 4800,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.3,
      tiers: [
        { name: 'Free CRM', annualPerSeat: 0, maxUsers: 999, recommended: true },
        { name: 'Starter', annualPerSeat: 216 },
        { name: 'Professional', annualPerSeat: 4800, minUsers: 5 },
      ],
    },
  },

  // --- Finance ---
  {
    slug: 'xero',
    name: 'Xero',
    provider: 'Xero',
    category: 'Finance',
    score: {
      jurisdiction: 2,
      continuity: 2,
      surveillance: 2,
      lockIn: 3,
      costExposure: 3,
      isAutoScored: true,
    },
    keyRisks:
      'NZ-headquartered with UK/AU data centres; reasonable data export; some lock-in through integrations; annual price rises',
    estimatedAnnualCost: 360,
    pricing: {
      model: 'flat',
      flatAnnual: 360,
      penetrationRate: 0.1,
      tiers: [
        { name: 'Starter', annualPerSeat: 0, maxUsers: 1, recommended: true },
        { name: 'Standard', annualPerSeat: 0, maxUsers: 3 },
        { name: 'Premium', annualPerSeat: 0, maxUsers: 10 },
      ],
      notes: 'Flat rate, not per-user. Starter: \u00A330/mo, Standard: \u00A342/mo, Premium: \u00A354/mo',
    },
  },
  {
    slug: 'quickbooks',
    name: 'QuickBooks',
    provider: 'Intuit',
    category: 'Finance',
    score: {
      jurisdiction: 4,
      continuity: 2,
      surveillance: 3,
      lockIn: 3,
      costExposure: 3,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; data export available but format limitations; pricing tiers can escalate; desktop version being phased out',
    estimatedAnnualCost: 480,
  },
  {
    slug: 'sage',
    name: 'Sage',
    provider: 'Sage',
    category: 'Finance',
    score: {
      jurisdiction: 2,
      continuity: 2,
      surveillance: 2,
      lockIn: 3,
      costExposure: 3,
      isAutoScored: true,
    },
    keyRisks:
      'UK-headquartered; long track record but moving to cloud-only; moderate lock-in; pricing complexity across products',
    estimatedAnnualCost: 600,
  },

  // --- Marketing ---
  {
    slug: 'mailchimp',
    name: 'Mailchimp',
    provider: 'Intuit',
    category: 'Marketing',
    score: {
      jurisdiction: 4,
      continuity: 3,
      surveillance: 3,
      lockIn: 2,
      costExposure: 3,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction (acquired by Intuit); list export available; costs escalate with list size; free tier significantly reduced',
    estimatedAnnualCost: 240,
    pricing: {
      model: 'flat',
      flatAnnual: 156,
      penetrationRate: 0.05,
    },
  },
  {
    slug: 'eventbrite',
    name: 'Eventbrite',
    provider: 'Eventbrite',
    category: 'Events',
    score: {
      jurisdiction: 4,
      continuity: 3,
      surveillance: 3,
      lockIn: 2,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; attendee data exportable; relatively low lock-in; per-ticket fees can add up for large events',
    estimatedAnnualCost: 0,
  },
  {
    slug: 'canva',
    name: 'Canva',
    provider: 'Canva',
    category: 'Design',
    score: {
      jurisdiction: 3,
      continuity: 2,
      surveillance: 3,
      lockIn: 2,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'Australian HQ but US data processing; designs exportable as images; low switching cost; generous free tier',
    estimatedAnnualCost: 120,
    pricing: {
      model: 'per_seat',
      penetrationRate: 0.2,
      annualPerSeat: 100,
    },
  },

  // --- Website & CMS ---
  {
    slug: 'wordpress',
    name: 'WordPress',
    provider: 'Automattic',
    category: 'CMS',
    score: {
      jurisdiction: 2,
      continuity: 1,
      surveillance: 1,
      lockIn: 1,
      costExposure: 1,
      isAutoScored: true,
    },
    keyRisks:
      'Open source with self-hosting option; full data portability; minimal surveillance; hosting costs vary but options abundant',
    estimatedAnnualCost: 300,
  },

  // --- Storage & Files ---
  {
    slug: 'dropbox',
    name: 'Dropbox',
    provider: 'Dropbox',
    category: 'Storage',
    score: {
      jurisdiction: 4,
      continuity: 2,
      surveillance: 3,
      lockIn: 2,
      costExposure: 3,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; files easily downloadable; some lock-in through Dropbox-specific features; pricing has increased',
    estimatedAnnualCost: 960,
  },
  {
    slug: 'onedrive',
    name: 'OneDrive',
    provider: 'Microsoft',
    category: 'Storage',
    score: {
      jurisdiction: 4,
      continuity: 2,
      surveillance: 3,
      lockIn: 3,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; bundled with M365; files downloadable but deeply integrated with Office apps; included in M365 licence',
    estimatedAnnualCost: 0,
  },

  // --- Project Management ---
  {
    slug: 'trello',
    name: 'Trello',
    provider: 'Atlassian',
    category: 'Project Management',
    score: {
      jurisdiction: 4,
      continuity: 3,
      surveillance: 2,
      lockIn: 2,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction (Atlassian); JSON export available; low lock-in; generous free tier but power-ups require paid plan',
    estimatedAnnualCost: 0,
  },
  {
    slug: 'asana',
    name: 'Asana',
    provider: 'Asana',
    category: 'Project Management',
    score: {
      jurisdiction: 4,
      continuity: 3,
      surveillance: 2,
      lockIn: 3,
      costExposure: 3,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; CSV export available; moderate lock-in through workflows; costs increase significantly with team size',
    estimatedAnnualCost: 1320,
  },
  {
    slug: 'airtable',
    name: 'Airtable',
    provider: 'Airtable',
    category: 'Project Management',
    score: {
      jurisdiction: 4,
      continuity: 3,
      surveillance: 2,
      lockIn: 4,
      costExposure: 4,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; CSV export but automations/views not portable; significant lock-in through custom apps; expensive at scale',
    estimatedAnnualCost: 2400,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.5,
      tiers: [
        { name: 'Free', annualPerSeat: 0, maxUsers: 5, recommended: true },
        { name: 'Team', annualPerSeat: 200 },
        { name: 'Business', annualPerSeat: 288, minUsers: 20 },
      ],
    },
  },

  // --- Social Media ---
  {
    slug: 'linkedin',
    name: 'LinkedIn',
    provider: 'Microsoft',
    category: 'Social Media',
    score: {
      jurisdiction: 4,
      continuity: 3,
      surveillance: 4,
      lockIn: 3,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; extensive professional data profiling; content not easily portable; free for basic use but analytics require paid tier',
    estimatedAnnualCost: 0,
  },
  {
    slug: 'meta-facebook',
    name: 'Meta/Facebook',
    provider: 'Meta',
    category: 'Social Media',
    score: {
      jurisdiction: 4,
      continuity: 3,
      surveillance: 5,
      lockIn: 4,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; extreme surveillance and data harvesting; audience locked to platform; ad costs increasing; algorithm changes unpredictable',
    estimatedAnnualCost: 0,
  },
  {
    slug: 'twitter-x',
    name: 'Twitter/X',
    provider: 'X Corp',
    category: 'Social Media',
    score: {
      jurisdiction: 4,
      continuity: 4,
      surveillance: 4,
      lockIn: 2,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; platform stability concerns under new ownership; content not portable; API access restricted; free to use but volatile',
    estimatedAnnualCost: 0,
  },
  {
    slug: 'instagram',
    name: 'Instagram',
    provider: 'Meta',
    category: 'Social Media',
    score: {
      jurisdiction: 4,
      continuity: 3,
      surveillance: 5,
      lockIn: 4,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; Meta surveillance infrastructure; content locked to platform; algorithm-dependent reach; ad costs rising',
    estimatedAnnualCost: 0,
  },

  // --- Messaging ---
  {
    slug: 'whatsapp',
    name: 'WhatsApp',
    provider: 'Meta',
    category: 'Messaging',
    score: {
      jurisdiction: 4,
      continuity: 3,
      surveillance: 4,
      lockIn: 3,
      costExposure: 1,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; end-to-end encrypted but metadata collected by Meta; contact list dependency; free but owned by Meta',
    estimatedAnnualCost: 0,
  },
  {
    slug: 'signal',
    name: 'Signal',
    provider: 'Signal Foundation',
    category: 'Messaging',
    score: {
      jurisdiction: 2,
      continuity: 2,
      surveillance: 1,
      lockIn: 1,
      costExposure: 1,
      isAutoScored: true,
    },
    keyRisks:
      'US-based non-profit but minimal data collection; open source; strong encryption; no lock-in; free and donation-funded',
    estimatedAnnualCost: 0,
    pricing: { model: 'free' },
  },

  // --- Privacy-focused alternatives ---
  {
    slug: 'jitsi-meet',
    name: 'Jitsi Meet',
    provider: '8x8 / Community',
    category: 'Communication',
    score: {
      jurisdiction: 1,
      continuity: 2,
      surveillance: 1,
      lockIn: 1,
      costExposure: 1,
      isAutoScored: true,
    },
    keyRisks:
      'Open source and self-hostable; minimal data collection; no lock-in; free; depends on community maintenance',
    estimatedAnnualCost: 0,
    pricing: { model: 'free' },
  },
  {
    slug: 'proton-mail',
    name: 'Proton Mail',
    provider: 'Proton AG',
    category: 'Email',
    score: {
      jurisdiction: 1,
      continuity: 2,
      surveillance: 1,
      lockIn: 2,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'Swiss jurisdiction with strong privacy laws; end-to-end encrypted; email export available; affordable paid tiers',
    estimatedAnnualCost: 480,
    pricing: { model: 'free' },
  },

  // --- AI Tools ---
  {
    slug: 'chatgpt',
    name: 'ChatGPT',
    provider: 'OpenAI',
    category: 'AI',
    score: {
      jurisdiction: 4,
      continuity: 3,
      surveillance: 5,
      lockIn: 3,
      costExposure: 4,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; inputs may be used for training unless opted out; no data portability for conversation history; rapid pricing changes; prompt injection risks when processing external data; staff may share sensitive beneficiary data inadvertently',
    estimatedAnnualCost: 240,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.3,
      tiers: [
        { name: 'Free', annualPerSeat: 0, maxUsers: 999, recommended: true },
        { name: 'Plus', annualPerSeat: 240 },
        { name: 'Team', annualPerSeat: 300, minUsers: 2 },
        { name: 'Enterprise', annualPerSeat: 720, minUsers: 50 },
      ],
    },
  },
  {
    slug: 'claude',
    name: 'Claude',
    provider: 'Anthropic',
    category: 'AI',
    score: {
      jurisdiction: 4,
      continuity: 3,
      surveillance: 3,
      lockIn: 2,
      costExposure: 3,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; does not train on user inputs by default; conversation history not portable; newer company with less track record; API pricing can scale quickly at volume',
    estimatedAnnualCost: 240,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.2,
      tiers: [
        { name: 'Free', annualPerSeat: 0, maxUsers: 999, recommended: true },
        { name: 'Pro', annualPerSeat: 240 },
        { name: 'Team', annualPerSeat: 360, minUsers: 5 },
        { name: 'Enterprise', annualPerSeat: 720, minUsers: 50 },
      ],
    },
  },
  {
    slug: 'microsoft-copilot',
    name: 'Microsoft Copilot',
    provider: 'Microsoft',
    category: 'AI',
    score: {
      jurisdiction: 4,
      continuity: 2,
      surveillance: 4,
      lockIn: 5,
      costExposure: 5,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; deeply embedded in M365 creating extreme lock-in; accesses all organisational data across SharePoint, Teams, email; expensive per-seat add-on; requires M365 E3/E5 base licence; data processing unclear across tenants',
    estimatedAnnualCost: 3600,
    pricing: {
      model: 'per_seat',
      penetrationRate: 0.5,
      annualPerSeat: 360,
      tiers: [
        { name: 'Copilot for Microsoft 365', annualPerSeat: 360, recommended: true, minUsers: 1 },
      ],
      notes: 'Requires Microsoft 365 E3/E5 or Business Standard base licence',
    },
  },
  {
    slug: 'google-gemini',
    name: 'Google Gemini',
    provider: 'Google',
    category: 'AI',
    score: {
      jurisdiction: 4,
      continuity: 3,
      surveillance: 5,
      lockIn: 4,
      costExposure: 3,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; Google data practices apply — inputs may inform ad profiling; tightly integrated with Google Workspace creating lock-in; Gemini for Workspace is a paid add-on; data processing terms vary by plan',
    estimatedAnnualCost: 240,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.3,
      tiers: [
        { name: 'Free', annualPerSeat: 0, maxUsers: 999, recommended: true },
        { name: 'Advanced', annualPerSeat: 240 },
        { name: 'Workspace add-on', annualPerSeat: 360, minUsers: 1 },
      ],
    },
  },
  {
    slug: 'notion-ai',
    name: 'Notion AI',
    provider: 'Notion',
    category: 'AI',
    score: {
      jurisdiction: 4,
      continuity: 3,
      surveillance: 3,
      lockIn: 4,
      costExposure: 3,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; AI processes all workspace content; significant lock-in through Notion database structure; AI is an add-on cost per member; data export available but complex structures lost',
    estimatedAnnualCost: 1200,
    pricing: {
      model: 'per_seat',
      penetrationRate: 0.5,
      annualPerSeat: 120,
      tiers: [
        { name: 'Plus + AI', annualPerSeat: 120, recommended: true },
        { name: 'Business + AI', annualPerSeat: 216, minUsers: 10 },
      ],
      notes: 'AI is a £8/member/month add-on to any paid Notion plan',
    },
  },
  {
    slug: 'grammarly',
    name: 'Grammarly',
    provider: 'Grammarly',
    category: 'AI',
    score: {
      jurisdiction: 4,
      continuity: 2,
      surveillance: 4,
      lockIn: 1,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; processes all text typed across all applications; keystroke-level data collection; browser extension has broad permissions; low lock-in — easy to remove; affordable',
    estimatedAnnualCost: 144,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.3,
      tiers: [
        { name: 'Free', annualPerSeat: 0, maxUsers: 999, recommended: true },
        { name: 'Premium', annualPerSeat: 144 },
        { name: 'Business', annualPerSeat: 180, minUsers: 3 },
      ],
    },
  },
  {
    slug: 'midjourney',
    name: 'Midjourney',
    provider: 'Midjourney',
    category: 'AI',
    score: {
      jurisdiction: 4,
      continuity: 3,
      surveillance: 2,
      lockIn: 2,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; generated images may have copyright implications; prompts and outputs visible to others on free/basic tiers; images downloadable so low lock-in; operates via Discord which adds another platform dependency',
    estimatedAnnualCost: 120,
    pricing: {
      model: 'flat',
      flatAnnual: 120,
      penetrationRate: 0.05,
      notes: 'Basic plan £10/month; primarily used by comms/design staff',
    },
  },
  {
    slug: 'dall-e',
    name: 'DALL-E',
    provider: 'OpenAI',
    category: 'AI',
    score: {
      jurisdiction: 4,
      continuity: 3,
      surveillance: 3,
      lockIn: 1,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; image generation via ChatGPT Plus or API; prompts may be used for training; generated images downloadable; low lock-in; credit-based pricing can be unpredictable',
    estimatedAnnualCost: 0,
    pricing: {
      model: 'free',
      notes: 'Included with ChatGPT Plus subscription or pay-per-image via API',
    },
  },
  {
    slug: 'zapier',
    name: 'Zapier',
    provider: 'Zapier',
    category: 'AI',
    score: {
      jurisdiction: 4,
      continuity: 3,
      surveillance: 3,
      lockIn: 4,
      costExposure: 4,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; processes data flowing between all connected systems; significant lock-in through complex automation workflows; costs escalate sharply with task volume; now embedding AI features that process content',
    estimatedAnnualCost: 240,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.1,
      tiers: [
        { name: 'Free', annualPerSeat: 0, maxUsers: 999, recommended: true },
        { name: 'Starter', annualPerSeat: 240 },
        { name: 'Professional', annualPerSeat: 600 },
        { name: 'Team', annualPerSeat: 840, minUsers: 3 },
      ],
      notes: 'Pricing based on tasks/month not seats; costs can spike with usage',
    },
  },
  {
    slug: 'make',
    name: 'Make (Integromat)',
    provider: 'Make',
    category: 'AI',
    score: {
      jurisdiction: 2,
      continuity: 3,
      surveillance: 2,
      lockIn: 3,
      costExposure: 3,
      isAutoScored: true,
    },
    keyRisks:
      'EU-headquartered (Czech Republic); GDPR-compliant data processing; moderate lock-in through automation scenarios; cheaper than Zapier but same escalation pattern; AI features being added',
    estimatedAnnualCost: 120,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.1,
      tiers: [
        { name: 'Free', annualPerSeat: 0, maxUsers: 999, recommended: true },
        { name: 'Core', annualPerSeat: 120 },
        { name: 'Pro', annualPerSeat: 240 },
      ],
    },
  },
  {
    slug: 'otter-ai',
    name: 'Otter.ai',
    provider: 'Otter.ai',
    category: 'AI',
    score: {
      jurisdiction: 4,
      continuity: 3,
      surveillance: 4,
      lockIn: 2,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; records and transcribes all meeting audio; stores conversation content in cloud; joins meetings automatically if configured; transcripts exportable; low lock-in',
    estimatedAnnualCost: 120,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.2,
      tiers: [
        { name: 'Free', annualPerSeat: 0, maxUsers: 999, recommended: true },
        { name: 'Pro', annualPerSeat: 120 },
        { name: 'Business', annualPerSeat: 240, minUsers: 3 },
      ],
    },
  },
  {
    slug: 'fireflies-ai',
    name: 'Fireflies.ai',
    provider: 'Fireflies',
    category: 'AI',
    score: {
      jurisdiction: 4,
      continuity: 3,
      surveillance: 4,
      lockIn: 2,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; records and stores all meeting audio and transcripts; integrates with calendar to auto-join meetings; processes sensitive meeting content; transcripts exportable',
    estimatedAnnualCost: 120,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.15,
      tiers: [
        { name: 'Free', annualPerSeat: 0, maxUsers: 999, recommended: true },
        { name: 'Pro', annualPerSeat: 120 },
        { name: 'Business', annualPerSeat: 228, minUsers: 3 },
      ],
    },
  },
  {
    slug: 'perplexity',
    name: 'Perplexity',
    provider: 'Perplexity AI',
    category: 'AI',
    score: {
      jurisdiction: 4,
      continuity: 3,
      surveillance: 3,
      lockIn: 1,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; search queries and interactions stored; newer company with less track record; low lock-in — web-based search replacement; affordable Pro tier',
    estimatedAnnualCost: 240,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.15,
      tiers: [
        { name: 'Free', annualPerSeat: 0, maxUsers: 999, recommended: true },
        { name: 'Pro', annualPerSeat: 240 },
      ],
    },
  },
  {
    slug: 'canva-ai',
    name: 'Canva Magic Studio',
    provider: 'Canva',
    category: 'AI',
    score: {
      jurisdiction: 3,
      continuity: 2,
      surveillance: 3,
      lockIn: 3,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'Australian HQ but US data processing; AI processes design content and brand assets; included in Canva Pro/Teams so no extra cost; designs exportable; moderate lock-in through brand kits and templates',
    estimatedAnnualCost: 0,
    pricing: {
      model: 'free',
      notes: 'Included with Canva Pro (£100/year/seat) or Teams subscription',
    },
  },
  {
    slug: 'power-automate',
    name: 'Power Automate',
    provider: 'Microsoft',
    category: 'AI',
    score: {
      jurisdiction: 4,
      continuity: 2,
      surveillance: 3,
      lockIn: 5,
      costExposure: 4,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; deep M365 integration creates extreme lock-in; AI Builder add-on processes documents and forms; workflows not portable; premium connectors require additional licensing; costs compound across the M365 ecosystem',
    estimatedAnnualCost: 180,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.2,
      tiers: [
        { name: 'Included in M365', annualPerSeat: 0, maxUsers: 999, recommended: true },
        { name: 'Premium', annualPerSeat: 180, minUsers: 1 },
        { name: 'Premium with AI Builder', annualPerSeat: 360, minUsers: 1 },
      ],
      notes: 'Basic included in M365; premium connectors and AI Builder are add-ons',
    },
  },

  // --- AI: Privacy-focused & local models ---
  {
    slug: 'mistral',
    name: 'Mistral AI',
    provider: 'Mistral AI',
    category: 'AI',
    score: {
      jurisdiction: 1,
      continuity: 3,
      surveillance: 2,
      lockIn: 2,
      costExposure: 3,
      isAutoScored: true,
    },
    keyRisks:
      'French/EU jurisdiction — strong GDPR compliance; models available for self-hosting; Le Chat free tier available; API pricing competitive but can scale; newer company with less track record than OpenAI',
    estimatedAnnualCost: 240,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.2,
      tiers: [
        { name: 'Le Chat Free', annualPerSeat: 0, maxUsers: 999, recommended: true },
        { name: 'Le Chat Pro', annualPerSeat: 240 },
        { name: 'API (pay-as-you-go)', annualPerSeat: 120 },
      ],
      notes: 'EU-headquartered. Models also available for self-hosting via open weights',
    },
  },
  {
    slug: 'ollama',
    name: 'Ollama',
    provider: 'Ollama (open source)',
    category: 'AI',
    score: {
      jurisdiction: 1,
      continuity: 2,
      surveillance: 1,
      lockIn: 1,
      costExposure: 1,
      isAutoScored: true,
    },
    keyRisks:
      'Runs entirely on your own hardware — no data leaves your network; open source; supports many model formats (Llama, Mistral, Gemma, etc.); zero vendor dependency; requires technical setup and capable hardware; no ongoing cost beyond electricity',
    estimatedAnnualCost: 0,
    pricing: {
      model: 'free',
      notes: 'Free and open source. Runs locally — needs a machine with 8GB+ RAM (16GB+ recommended for larger models)',
    },
  },
  {
    slug: 'lm-studio',
    name: 'LM Studio',
    provider: 'LM Studio',
    category: 'AI',
    score: {
      jurisdiction: 1,
      continuity: 2,
      surveillance: 1,
      lockIn: 1,
      costExposure: 1,
      isAutoScored: true,
    },
    keyRisks:
      'Desktop app for running AI models locally; no data sent externally; supports GGUF models from Hugging Face; free for personal use; no lock-in — uses standard model formats; requires decent hardware',
    estimatedAnnualCost: 0,
    pricing: {
      model: 'free',
      notes: 'Free for personal and community use. Runs locally on Mac/Windows/Linux',
    },
  },
  {
    slug: 'jan-ai',
    name: 'Jan',
    provider: 'Jan (open source)',
    category: 'AI',
    score: {
      jurisdiction: 1,
      continuity: 2,
      surveillance: 1,
      lockIn: 1,
      costExposure: 1,
      isAutoScored: true,
    },
    keyRisks:
      'Open source ChatGPT alternative that runs entirely offline; no data leaves your device; supports multiple model formats; free; early-stage project but active development; requires 8GB+ RAM',
    estimatedAnnualCost: 0,
    pricing: {
      model: 'free',
      notes: 'Free and open source. Privacy-first alternative to ChatGPT',
    },
  },
  {
    slug: 'greenpt',
    name: 'GreenPT',
    provider: 'GreenPT',
    category: 'AI',
    score: {
      jurisdiction: 1,
      continuity: 3,
      surveillance: 1,
      lockIn: 1,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'EU-based; focused on sustainable and ethical AI; lower carbon footprint than US hyperscalers; smaller model selection but growing; privacy-first approach; newer service with less established track record',
    estimatedAnnualCost: 120,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.1,
      tiers: [
        { name: 'Free', annualPerSeat: 0, maxUsers: 999, recommended: true },
        { name: 'Pro', annualPerSeat: 120 },
      ],
      notes: 'EU-hosted, sustainability-focused AI assistant',
    },
  },
  {
    slug: 'hugging-face',
    name: 'Hugging Face',
    provider: 'Hugging Face',
    category: 'AI',
    score: {
      jurisdiction: 2,
      continuity: 2,
      surveillance: 1,
      lockIn: 1,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'US company but open-source ethos; hosts thousands of free models; Inference API for cloud usage; models downloadable for local use; no lock-in — standard model formats; Spaces can be self-hosted',
    estimatedAnnualCost: 0,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.05,
      tiers: [
        { name: 'Free', annualPerSeat: 0, maxUsers: 999, recommended: true },
        { name: 'Pro', annualPerSeat: 108 },
        { name: 'Enterprise', annualPerSeat: 240, minUsers: 5 },
      ],
      notes: 'Hub is free. Pro for faster inference. Models downloadable for self-hosting',
    },
  },
  {
    slug: 'open-webui',
    name: 'Open WebUI',
    provider: 'Open WebUI (open source)',
    category: 'AI',
    score: {
      jurisdiction: 1,
      continuity: 2,
      surveillance: 1,
      lockIn: 1,
      costExposure: 1,
      isAutoScored: true,
    },
    keyRisks:
      'Self-hosted ChatGPT-style interface for local models; connects to Ollama or any OpenAI-compatible API; all data stays on your server; fully open source; requires technical setup; multi-user support',
    estimatedAnnualCost: 0,
    pricing: {
      model: 'free',
      notes: 'Free and open source. Self-hosted web UI for Ollama and other local AI models',
    },
  },
  {
    slug: 'llama',
    name: 'Meta Llama',
    provider: 'Meta',
    category: 'AI',
    score: {
      jurisdiction: 1,
      continuity: 2,
      surveillance: 1,
      lockIn: 1,
      costExposure: 1,
      isAutoScored: true,
    },
    keyRisks:
      'Open-weight models — run anywhere with no data sent to Meta; available via Ollama, LM Studio, etc.; no ongoing cost; various sizes (8B to 405B parameters) for different hardware; Meta licence has some commercial use restrictions for very large deployments',
    estimatedAnnualCost: 0,
    pricing: {
      model: 'free',
      notes: 'Free open-weight models. Run via Ollama or LM Studio on your own hardware',
    },
  },
  {
    slug: 'privateai',
    name: 'Private AI',
    provider: 'Private AI',
    category: 'AI',
    score: {
      jurisdiction: 2,
      continuity: 3,
      surveillance: 1,
      lockIn: 2,
      costExposure: 3,
      isAutoScored: true,
    },
    keyRisks:
      'Canadian jurisdiction; specialises in PII detection and redaction; can run on-premises; designed for data privacy compliance; useful for organisations handling sensitive beneficiary data; commercial licensing',
    estimatedAnnualCost: 2400,
    pricing: {
      model: 'flat',
      flatAnnual: 2400,
      penetrationRate: 0.05,
      notes: 'Enterprise data privacy tool. On-premises option available. Contact for pricing.',
    },
  },

  // --- Website & Hosting ---
  {
    slug: 'squarespace',
    name: 'Squarespace',
    provider: 'Squarespace',
    category: 'CMS',
    score: {
      jurisdiction: 4,
      continuity: 2,
      surveillance: 3,
      lockIn: 4,
      costExposure: 3,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; significant lock-in — content not easily portable to other platforms; proprietary templates; costs increase with e-commerce features; no self-hosting option',
    estimatedAnnualCost: 192,
    pricing: {
      model: 'flat',
      flatAnnual: 192,
      penetrationRate: 0.05,
      tiers: [
        { name: 'Personal', annualPerSeat: 0, maxUsers: 999, recommended: true },
        { name: 'Business', annualPerSeat: 0, maxUsers: 999 },
        { name: 'Commerce Basic', annualPerSeat: 0, maxUsers: 999 },
      ],
      notes: 'Personal: £12/mo, Business: £18/mo, Commerce: £26/mo (billed annually)',
    },
  },
  {
    slug: 'wix',
    name: 'Wix',
    provider: 'Wix',
    category: 'CMS',
    score: {
      jurisdiction: 3,
      continuity: 2,
      surveillance: 3,
      lockIn: 5,
      costExposure: 3,
      isAutoScored: true,
    },
    keyRisks:
      'Israel/US jurisdiction; extreme lock-in — sites cannot be migrated to other platforms; proprietary editor; AI features now process site content; costs increase significantly for business features',
    estimatedAnnualCost: 156,
    pricing: {
      model: 'flat',
      flatAnnual: 156,
      penetrationRate: 0.05,
      notes: 'Light: £8.50/mo, Core: £13/mo, Business: £17.50/mo (billed annually)',
    },
  },
  {
    slug: 'webflow',
    name: 'Webflow',
    provider: 'Webflow',
    category: 'CMS',
    score: {
      jurisdiction: 4,
      continuity: 3,
      surveillance: 2,
      lockIn: 4,
      costExposure: 3,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; visual builder creates moderate lock-in; can export HTML/CSS but CMS content not easily portable; costs per-site and per-CMS item; AI features being added',
    estimatedAnnualCost: 168,
    pricing: {
      model: 'flat',
      flatAnnual: 168,
      penetrationRate: 0.05,
      notes: 'Basic: £14/mo, CMS: £23/mo, Business: £39/mo (billed annually)',
    },
  },
  {
    slug: 'netlify',
    name: 'Netlify',
    provider: 'Netlify',
    category: 'Hosting',
    score: {
      jurisdiction: 4,
      continuity: 2,
      surveillance: 1,
      lockIn: 2,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; low lock-in — deploys standard web projects; generous free tier; costs can spike with high traffic; sites are portable',
    estimatedAnnualCost: 0,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.05,
      tiers: [
        { name: 'Free', annualPerSeat: 0, maxUsers: 999, recommended: true },
        { name: 'Pro', annualPerSeat: 228 },
      ],
    },
  },
  {
    slug: 'vercel',
    name: 'Vercel',
    provider: 'Vercel',
    category: 'Hosting',
    score: {
      jurisdiction: 4,
      continuity: 2,
      surveillance: 1,
      lockIn: 3,
      costExposure: 3,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; some lock-in through Next.js optimisations and serverless functions; generous free tier but costs can spike unexpectedly with traffic; sites are portable',
    estimatedAnnualCost: 0,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.05,
      tiers: [
        { name: 'Hobby', annualPerSeat: 0, maxUsers: 999, recommended: true },
        { name: 'Pro', annualPerSeat: 240 },
      ],
    },
  },
  {
    slug: 'cloudflare',
    name: 'Cloudflare',
    provider: 'Cloudflare',
    category: 'Hosting',
    score: {
      jurisdiction: 4,
      continuity: 1,
      surveillance: 2,
      lockIn: 2,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; DNS and CDN creates some dependency; generous free tier; Pages and Workers are portable; transparent pricing',
    estimatedAnnualCost: 0,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.05,
      tiers: [
        { name: 'Free', annualPerSeat: 0, maxUsers: 999, recommended: true },
        { name: 'Pro', annualPerSeat: 240 },
      ],
    },
  },
  {
    slug: 'aws',
    name: 'Amazon Web Services',
    provider: 'Amazon',
    category: 'Hosting',
    score: {
      jurisdiction: 4,
      continuity: 1,
      surveillance: 3,
      lockIn: 5,
      costExposure: 5,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; extreme lock-in through proprietary services; complex and unpredictable pricing; requires technical expertise; data egress fees; extensive access to infrastructure data',
    estimatedAnnualCost: 1200,
    pricing: {
      model: 'flat',
      flatAnnual: 1200,
      penetrationRate: 0.05,
      notes: 'Highly variable — £100/mo is typical for small org; can range from £0 to £10,000+',
    },
  },
  {
    slug: 'azure',
    name: 'Microsoft Azure',
    provider: 'Microsoft',
    category: 'Hosting',
    score: {
      jurisdiction: 4,
      continuity: 1,
      surveillance: 3,
      lockIn: 5,
      costExposure: 5,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; extreme lock-in through M365 integration and proprietary services; complex pricing; deep coupling with Active Directory; data egress fees; UK data centres available',
    estimatedAnnualCost: 1200,
    pricing: {
      model: 'flat',
      flatAnnual: 1200,
      penetrationRate: 0.05,
      notes: 'Highly variable; often bundled with M365 Enterprise agreements',
    },
  },

  // --- Payment & Donations ---
  {
    slug: 'stripe',
    name: 'Stripe',
    provider: 'Stripe',
    category: 'Payment',
    score: {
      jurisdiction: 3,
      continuity: 1,
      surveillance: 2,
      lockIn: 3,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'US/Ireland dual jurisdiction; good API documentation for migration; moderate lock-in through Stripe-specific checkout and subscription features; transparent per-transaction pricing (1.4% + 20p UK cards)',
    estimatedAnnualCost: 0,
    pricing: {
      model: 'free',
      notes: 'No monthly fee — 1.4% + 20p per UK card transaction, 2.9% + 20p international',
    },
  },
  {
    slug: 'gocardless',
    name: 'GoCardless',
    provider: 'GoCardless',
    category: 'Payment',
    score: {
      jurisdiction: 2,
      continuity: 2,
      surveillance: 1,
      lockIn: 2,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'UK-headquartered; Direct Debit specialist — good for recurring donations; mandate data portable; low per-transaction fees (1% + 20p capped at £4); low lock-in',
    estimatedAnnualCost: 0,
    pricing: {
      model: 'free',
      notes: 'No monthly fee — 1% + 20p per transaction (capped at £4). Ideal for recurring donations',
    },
  },
  {
    slug: 'paypal',
    name: 'PayPal',
    provider: 'PayPal',
    category: 'Payment',
    score: {
      jurisdiction: 4,
      continuity: 2,
      surveillance: 3,
      lockIn: 3,
      costExposure: 3,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; donor data locked in PayPal ecosystem; higher fees than alternatives (2.9% + 30p); account freezing risks for charities; discounted non-profit rates available but must apply',
    estimatedAnnualCost: 0,
    pricing: {
      model: 'free',
      notes: 'Standard: 2.9% + 30p per transaction. Charity rate: 1.4% + 20p (must apply)',
    },
  },
  {
    slug: 'donorfy',
    name: 'Donorfy',
    provider: 'Donorfy',
    category: 'CRM',
    score: {
      jurisdiction: 1,
      continuity: 2,
      surveillance: 1,
      lockIn: 3,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'UK-headquartered; purpose-built for charities; data exportable; moderate lock-in through donor management workflows; affordable; integrates with Gift Aid',
    estimatedAnnualCost: 600,
    pricing: {
      model: 'flat',
      flatAnnual: 600,
      penetrationRate: 0.1,
      notes: 'From £50/month; pricing based on contact volume not seats',
    },
  },
  {
    slug: 'justgiving',
    name: 'JustGiving',
    provider: 'Blackbaud',
    category: 'Payment',
    score: {
      jurisdiction: 4,
      continuity: 2,
      surveillance: 2,
      lockIn: 3,
      costExposure: 3,
      isAutoScored: true,
    },
    keyRisks:
      'US parent company (Blackbaud); platform fee on donations (currently 0%+payment fees but has changed before); donor relationships partly owned by platform; data export available but limited; Blackbaud had major data breach in 2020',
    estimatedAnnualCost: 0,
    pricing: {
      model: 'free',
      notes: '0% platform fee + 1.9% + 20p payment processing. Gift Aid auto-claimed',
    },
  },
  {
    slug: 'beacon',
    name: 'Beacon',
    provider: 'Beacon',
    category: 'CRM',
    score: {
      jurisdiction: 1,
      continuity: 2,
      surveillance: 1,
      lockIn: 3,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'UK-headquartered; purpose-built charity CRM; data exportable; moderate lock-in; integrates with payment processors; includes email marketing and forms',
    estimatedAnnualCost: 1200,
    pricing: {
      model: 'flat',
      flatAnnual: 1200,
      penetrationRate: 0.1,
      notes: 'From £100/month. All-in-one: CRM, email, forms, payments',
    },
  },
  {
    slug: 'givewp',
    name: 'GiveWP',
    provider: 'StellarWP',
    category: 'Payment',
    score: {
      jurisdiction: 4,
      continuity: 2,
      surveillance: 1,
      lockIn: 2,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'US provider but self-hosted on your WordPress site; full data ownership; low lock-in; donation data stays in your database; requires WordPress',
    estimatedAnnualCost: 180,
    pricing: {
      model: 'flat',
      flatAnnual: 180,
      penetrationRate: 0.05,
      notes: 'WordPress plugin. Basic: free. Pro: ~£15/month. You own all data.',
    },
  },

  // --- Databases ---
  {
    slug: 'google-sheets',
    name: 'Google Sheets',
    provider: 'Google',
    category: 'Database',
    score: {
      jurisdiction: 4,
      continuity: 2,
      surveillance: 5,
      lockIn: 2,
      costExposure: 1,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; Google data practices apply; widely used as de-facto database in small orgs; data exportable as CSV/Excel; part of Google Workspace pricing; formulas and scripts not portable',
    estimatedAnnualCost: 0,
    pricing: { model: 'free', notes: 'Free with Google account. Part of Google Workspace for orgs.' },
  },
  {
    slug: 'excel',
    name: 'Microsoft Excel',
    provider: 'Microsoft',
    category: 'Database',
    score: {
      jurisdiction: 4,
      continuity: 1,
      surveillance: 3,
      lockIn: 3,
      costExposure: 1,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; ubiquitous in sector; files portable but macros/VBA not; often used as critical database without backup; included in M365; desktop version still works offline',
    estimatedAnnualCost: 0,
    pricing: { model: 'free', notes: 'Included with Microsoft 365 subscription' },
  },
  {
    slug: 'access',
    name: 'Microsoft Access',
    provider: 'Microsoft',
    category: 'Database',
    score: {
      jurisdiction: 4,
      continuity: 4,
      surveillance: 2,
      lockIn: 5,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'Deprecated platform — Microsoft investing minimally; extreme lock-in through VBA and proprietary format; data exportable but application logic is not; critical for many legacy charity systems; single point of failure if the one person who built it leaves',
    estimatedAnnualCost: 0,
    pricing: { model: 'free', notes: 'Included in M365 Apps for Business/Enterprise. Legacy — avoid for new projects.' },
  },
  {
    slug: 'notion',
    name: 'Notion',
    provider: 'Notion',
    category: 'Database',
    score: {
      jurisdiction: 4,
      continuity: 3,
      surveillance: 3,
      lockIn: 4,
      costExposure: 3,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; increasingly used as lightweight database/CRM; significant lock-in through relational databases, views, and automations; markdown export available but structure lost; per-member pricing',
    estimatedAnnualCost: 960,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.5,
      tiers: [
        { name: 'Free', annualPerSeat: 0, maxUsers: 999, recommended: true },
        { name: 'Plus', annualPerSeat: 96 },
        { name: 'Business', annualPerSeat: 216, minUsers: 10 },
      ],
    },
  },
  {
    slug: 'baserow',
    name: 'Baserow',
    provider: 'Baserow (open source)',
    category: 'Database',
    score: {
      jurisdiction: 1,
      continuity: 2,
      surveillance: 1,
      lockIn: 1,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'EU-based (Netherlands); open source Airtable alternative; self-hostable; full data export; low lock-in; hosted version available; API-first design',
    estimatedAnnualCost: 0,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.3,
      tiers: [
        { name: 'Free', annualPerSeat: 0, maxUsers: 999, recommended: true },
        { name: 'Premium', annualPerSeat: 60 },
        { name: 'Self-hosted', annualPerSeat: 0, maxUsers: 999 },
      ],
      notes: 'Open-source Airtable alternative. Self-hosting is free.',
    },
  },
  {
    slug: 'nocodb',
    name: 'NocoDB',
    provider: 'NocoDB (open source)',
    category: 'Database',
    score: {
      jurisdiction: 1,
      continuity: 2,
      surveillance: 1,
      lockIn: 1,
      costExposure: 1,
      isAutoScored: true,
    },
    keyRisks:
      'Open source; turns any database into a smart spreadsheet interface; self-hostable; connects to existing MySQL/PostgreSQL; full data ownership; active community',
    estimatedAnnualCost: 0,
    pricing: { model: 'free', notes: 'Free and open source. Self-hosted. Cloud version also available.' },
  },
  {
    slug: 'supabase',
    name: 'Supabase',
    provider: 'Supabase',
    category: 'Database',
    score: {
      jurisdiction: 4,
      continuity: 2,
      surveillance: 1,
      lockIn: 1,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'US-headquartered but open source; built on PostgreSQL — fully portable; self-hostable; generous free tier; real-time subscriptions; auth and storage included; low lock-in due to standard PostgreSQL',
    estimatedAnnualCost: 0,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.05,
      tiers: [
        { name: 'Free', annualPerSeat: 0, maxUsers: 999, recommended: true },
        { name: 'Pro', annualPerSeat: 300 },
      ],
      notes: 'Open-source Firebase alternative built on PostgreSQL',
    },
  },

  // --- Data Visualisation & BI ---
  {
    slug: 'power-bi',
    name: 'Power BI',
    provider: 'Microsoft',
    category: 'Data Visualisation',
    score: {
      jurisdiction: 4,
      continuity: 2,
      surveillance: 3,
      lockIn: 4,
      costExposure: 3,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; deep M365 integration creates lock-in; DAX/M formulas not portable; free desktop version but sharing requires Pro licence; data models can become complex and dependent on specific connectors',
    estimatedAnnualCost: 1200,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.15,
      tiers: [
        { name: 'Desktop (free)', annualPerSeat: 0, maxUsers: 999, recommended: true },
        { name: 'Pro', annualPerSeat: 120 },
        { name: 'Premium per user', annualPerSeat: 240, minUsers: 1 },
      ],
      notes: 'Desktop is free. Pro (£10/month) needed to share reports. Often bundled with M365 E5.',
    },
  },
  {
    slug: 'tableau',
    name: 'Tableau',
    provider: 'Salesforce',
    category: 'Data Visualisation',
    score: {
      jurisdiction: 4,
      continuity: 2,
      surveillance: 2,
      lockIn: 4,
      costExposure: 5,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction (Salesforce); powerful but expensive; significant learning curve; workbooks not portable to other platforms; Creator licence very costly; lock-in through custom calculations and data extracts',
    estimatedAnnualCost: 5040,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.1,
      tiers: [
        { name: 'Viewer', annualPerSeat: 180 },
        { name: 'Explorer', annualPerSeat: 504 },
        { name: 'Creator', annualPerSeat: 840, recommended: true },
      ],
      notes: 'Expensive. Tableau Public is free but all data is public. Creator needed to build dashboards.',
    },
  },
  {
    slug: 'looker-studio',
    name: 'Looker Studio',
    provider: 'Google',
    category: 'Data Visualisation',
    score: {
      jurisdiction: 4,
      continuity: 2,
      surveillance: 4,
      lockIn: 3,
      costExposure: 1,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; Google data practices; free to use; good Google Sheets/Analytics integration; reports not portable but data sources are; moderate lock-in through custom connectors',
    estimatedAnnualCost: 0,
    pricing: { model: 'free', notes: 'Free. Formerly Google Data Studio. Best with Google data sources.' },
  },
  {
    slug: 'metabase',
    name: 'Metabase',
    provider: 'Metabase (open source)',
    category: 'Data Visualisation',
    score: {
      jurisdiction: 1,
      continuity: 2,
      surveillance: 1,
      lockIn: 1,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'Open source; self-hostable; connects to any SQL database; questions/dashboards exportable; low lock-in; cloud hosting available; good for non-technical users to explore data',
    estimatedAnnualCost: 0,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.1,
      tiers: [
        { name: 'Open Source', annualPerSeat: 0, maxUsers: 999, recommended: true },
        { name: 'Cloud Starter', annualPerSeat: 0, maxUsers: 5 },
        { name: 'Pro (self-hosted)', annualPerSeat: 120 },
      ],
      notes: 'Open source and self-hostable. Ask questions of your data without SQL.',
    },
  },
  {
    slug: 'evidence',
    name: 'Evidence',
    provider: 'Evidence (open source)',
    category: 'Data Visualisation',
    score: {
      jurisdiction: 1,
      continuity: 2,
      surveillance: 1,
      lockIn: 1,
      costExposure: 1,
      isAutoScored: true,
    },
    keyRisks:
      'Open source; reports written in markdown+SQL; fully version-controllable; self-hostable; no vendor dependency; requires some technical ability; newer project',
    estimatedAnnualCost: 0,
    pricing: { model: 'free', notes: 'Free and open source. Code-first BI — reports as markdown+SQL.' },
  },
  {
    slug: 'impact-reporting-spreadsheet',
    name: 'Impact Reporting Spreadsheet',
    provider: 'Internal',
    category: 'Data Visualisation',
    score: {
      jurisdiction: 1,
      continuity: 3,
      surveillance: 1,
      lockIn: 2,
      costExposure: 1,
      isAutoScored: true,
    },
    keyRisks:
      'Usually Excel or Google Sheets; single point of failure if author leaves; no validation or data integrity; hard to aggregate across programmes; free but fragile',
    estimatedAnnualCost: 0,
    pricing: { model: 'free', notes: 'Custom spreadsheet. Common in small charities for funder reporting.' },
  },

  // --- GIS & Geospatial ---
  {
    slug: 'qgis',
    name: 'QGIS',
    provider: 'QGIS (open source)',
    category: 'Geospatial',
    score: {
      jurisdiction: 1,
      continuity: 1,
      surveillance: 1,
      lockIn: 1,
      costExposure: 1,
      isAutoScored: true,
    },
    keyRisks:
      'Free and open source desktop GIS; no data leaves your machine; supports all standard formats; active community; steep learning curve; no vendor dependency',
    estimatedAnnualCost: 0,
    pricing: { model: 'free', notes: 'Free and open source. Professional-grade desktop GIS.' },
  },
  {
    slug: 'arcgis',
    name: 'ArcGIS Online',
    provider: 'Esri',
    category: 'Geospatial',
    score: {
      jurisdiction: 4,
      continuity: 2,
      surveillance: 2,
      lockIn: 5,
      costExposure: 5,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; industry standard but extremely expensive; significant lock-in through proprietary formats and extensions; data exportable but workflows are not; per-named-user licensing; often bundled with local authority agreements',
    estimatedAnnualCost: 6000,
    pricing: {
      model: 'per_seat',
      penetrationRate: 0.1,
      annualPerSeat: 600,
      tiers: [
        { name: 'Creator', annualPerSeat: 600, recommended: true },
        { name: 'GIS Professional', annualPerSeat: 1200 },
      ],
      notes: 'Expensive. Many councils have enterprise agreements. Charity/NGO discounts available.',
    },
  },
  {
    slug: 'google-maps-platform',
    name: 'Google Maps Platform',
    provider: 'Google',
    category: 'Geospatial',
    score: {
      jurisdiction: 4,
      continuity: 2,
      surveillance: 4,
      lockIn: 3,
      costExposure: 4,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; usage-based pricing can spike unpredictably; $200/month free credit; Google tracks all map interactions; API changes have broken implementations before; alternatives exist (Mapbox, OpenStreetMap)',
    estimatedAnnualCost: 0,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.05,
      tiers: [
        { name: 'Free ($200 credit)', annualPerSeat: 0, maxUsers: 999, recommended: true },
      ],
      notes: '$200/month free credit covers most small org usage. Pay-as-you-go beyond that.',
    },
  },
  {
    slug: 'mapbox',
    name: 'Mapbox',
    provider: 'Mapbox',
    category: 'Geospatial',
    score: {
      jurisdiction: 4,
      continuity: 2,
      surveillance: 2,
      lockIn: 2,
      costExposure: 3,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; usage-based pricing; good free tier (50k map loads/month); open-source map rendering library (MapLibre); lower lock-in than Google Maps; OpenStreetMap data',
    estimatedAnnualCost: 0,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.05,
      tiers: [
        { name: 'Free (50k loads)', annualPerSeat: 0, maxUsers: 999, recommended: true },
        { name: 'Pay-as-you-go', annualPerSeat: 0 },
      ],
      notes: 'Free for 50k map loads/month. Open-source alternative: MapLibre.',
    },
  },
  {
    slug: 'felt',
    name: 'Felt',
    provider: 'Felt',
    category: 'Geospatial',
    score: {
      jurisdiction: 4,
      continuity: 3,
      surveillance: 2,
      lockIn: 2,
      costExposure: 2,
      isAutoScored: true,
    },
    keyRisks:
      'US jurisdiction; collaborative web mapping tool; data importable/exportable in standard formats; low lock-in; generous free tier; good for non-technical users; newer company',
    estimatedAnnualCost: 0,
    pricing: {
      model: 'tiered',
      penetrationRate: 0.1,
      tiers: [
        { name: 'Free', annualPerSeat: 0, maxUsers: 999, recommended: true },
        { name: 'Team', annualPerSeat: 240, minUsers: 2 },
      ],
      notes: 'Collaborative mapping. Think "Google Docs for maps". Good for service area mapping.',
    },
  },
  {
    slug: 'carto',
    name: 'CARTO',
    provider: 'CARTO',
    category: 'Geospatial',
    score: {
      jurisdiction: 3,
      continuity: 3,
      surveillance: 2,
      lockIn: 3,
      costExposure: 4,
      isAutoScored: true,
    },
    keyRisks:
      'Spain/US jurisdiction; cloud-native spatial analytics; good for large datasets; moderate lock-in through CARTO-specific SQL extensions; expensive at scale; free tier for students/non-profits',
    estimatedAnnualCost: 2400,
    pricing: {
      model: 'flat',
      flatAnnual: 2400,
      penetrationRate: 0.05,
      notes: 'Free for qualifying non-profits. Commercial from $200/month.',
    },
  },
];
